### ISSUE TITLE
Long image file names mess up formatting

### ISSUE THREAD

**Issue by Kromey** [jonmsawyer/maio_old#1]
Exceptionally long image file names (e.g. "234e691320c0ad5b45ee3c96d0d7b8f8_20100912225809_958.jpg", as generated by a rather remarkable little piece of software "flgetpics.py") cause the controls/metadata sidebar to reflow to several pixels wider than it usually is, resulting in (wide) images themselves being pushed down below the sidebar and therefore off the screen entirely.

If navigating between multiple very-long-name images, subsequent views seem to pick up on the re-sized sidebar and display correctly, but the issue returns the moment a name short enough (or featuring aptly-placed line-breakable characters, e.g. '-' or ' ') is displayed followed by another very-long-name image.

Additionally, the very long filenames cause the browser window to display scroll bars even when the image isn't forced below the sidebar.

**Comment by Kromey** [comment]
Suggested resolution: File names should be displayed within a fixed-width element that hides overflow to prevent over-long content (i.e. over-long file names) from reflowing the page layout. The user should then have the option of a hover and/or click event to display a floated element with the full filename, but should be done in such a way as to avoid page reflow (e.g. an overlayed div anchored by the left edge to the sidebar).

**Comment by jonmsawyer** [comment]
Confirmed defect. Kromey fixed with patch. Thanks Kromey!
